run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: go-auto-release-test

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
